version: '3.4'

services:
  app:
    image: wvc-backend-app
    container_name: wvc-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env
