http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

mongo:
  databaseName: wvcPlatform

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days

limiter:
  rps: 10
  burst: 20
  ttl: 10m
