name: CI-prod

on:
  push:
    branches:
      - master

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Install git-secret
        env:
          SECRETS_VERBOSE: 1
          PREFIX: "/usr/local"
        run: |
          git clone https://github.com/sobolevn/git-secret.git git-secret
          cd git-secret
          sudo make build
          sudo make install

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SECRET_PWD }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Reveal secrets
        env:
          SECRET_PWD: ${{ secrets.SECRET_PWD }}
          SECRETS_VERBOSE: 1
        run: |
          git secret reveal -p $(echo $SECRET_PWD)

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          rm: true
          source: "./*"
          target: "api"

      - name: Deploy to Server via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd api
            docker-compose -f deploy/docker-compose.yml stop
            docker-compose -f deploy/docker-compose.yml rm -f
            docker-compose -f deploy/docker-compose.yml up --build
